nixos:
    password_hash: ENC[AES256_GCM,data:aKS3+dWfJ9x9loY8ut21pGNBpBpnOX7bAchZdhOumBwOQEh2BOgqijGsAxw8m/lzW209fq5xJCSPq6uiqC1Cnr7fUpAai4fSeA==,iv:xyOB2yPfAdG64IlSYN66n4Ng3lUs40FrbippqncPirI=,tag:QgThPJDfMF4IFwWiBCEbWg==,type:str]
    ssh_public: ENC[AES256_GCM,data:HDpofzsekRwW/YVJlINs82qfw9++ZW2d3Y7jvg0TRqAsW7FxduLpBvGC09tbDsHu0t/ukzxAtUbAns0i/97utivZwT/jeeEhiG9c9PB09heuWuxz8g4=,iv:E7gYrKZXs3O6F190pw/oKfQtP40ia7owfsefgM1R5P0=,tag:WpShsa9CfLCS8CAnO6y1iQ==,type:str]
sops:
    age:
        - recipient: age1gk8pnzm29uas2wsw5v5fjmlxxn6txv6gg5ad8yy7tvatlhgfw9rqyjrg0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QWYzdlQ5WDdxenJTWExW
            S05nYjUvWXJ3a1NKTWRiYnNzMVRCc2IyajFvCk4ydndpblBhNm5uek83SkNoZlFH
            SGgxSlIyb0NNdGxEeU1FVFNKQ0FnWFEKLS0tIElDWkc1YlNXUWRTbXBiMjBCZm43
            WVpLMlloejZmd0s5Q05OMTBzbkJLQUUKjYXCNBARwpt96nNSDNMWmsfRQK/oOPh/
            qjnveyCi9Ece4daBayZDqLi8uM5Qy/k3vDJ3LA5BCalr11f57e6esA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15hk7pe2gnh3h7cmnv4sf0gfp4p5gwul66nxtm4a22xhltam4du5s0zq8rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb3J4WmFoUTU4bEpLdjZI
            M1FYbGlEeGZCZG1oYW5ncWRpcDlGMUZCRmdjCmY5L2VudzZXQVNpbFJHNENJNnFm
            VllMU3ExSUZ0THk5Zy8wQS9ZRC9tR2cKLS0tIHowYU5kbmYvR1c0bFJuaU5aQXcv
            UXJTWUcxWDREcVZQdGIxN2dTYklIbWsKa1NnlhIS5nagSAlRC6ZJF1smpZsWPVgq
            H889I6fwLQHXkTZCIn0YPwIuzPDaMa75I18TRFlGDHUbMwW3NQVwkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezktueyxlkm6qg583jrjngecw662w4k480d5kj3cgh070uyz6f6qdwxx3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdzRHdG5yRk9kR1oxQWJm
            SzF5TjlHUDlXbDBUSmxLVTZ4cFhrdFVFaHlFCjF0UWF5WHpWb2h6RU1QaUtxYldP
            cXNqV1BTalVhS2xLMDVZdUloeHpBZmsKLS0tIEFBcXdWQnV0SXRrdkRlVUM2a2pj
            TW94NzdKYnFJbFJkMWZwRnM1d1ZVbnMKuvJcbtZvAGOUJtI/pWJB0SlaIHpRwdK8
            fpebabXlsu3SXIeNqEQdM7VVQHaPBdRCcJ7CUVoG6mYvxUbc/dr1RQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m3h9cfyuqdapfuw3dydx90qwcdpmtqts9yxp7gljd808595fzdxs0ea4t8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Skx4Z2s0YVBMbnBRSFBa
            QjFHeXBRblFuWnZjY2VpM1hLRW9nWkdZY2lzCmpwamhHc09WRER3Ym1FdG9BMmNC
            QlJxWkRFc1Jwek05VytjUWRnK0x0cG8KLS0tIEZ2YmdpaWZsNXVJMDkvYURwQ3Rl
            dWxBNFk0dnY3ZGJGUDYraWVDZWNWZVkKHW1trLwcz/wer+pmlv4n5/B7MwTpTknZ
            IFZ2QGjGemP7EQKxuqFZ6ADozKSXeWu4t92p31hb/6DEl8pVgwYsKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyrcctsjpxqd732emuhuyrp2nn3f8ejzxmanyt9pgwyzs46kgaesd08muf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbHFuN05zdkF4ZWNValRh
            VkdZOE16YmVHSVhaOUF5ZmRmRG00eHFqeUNZCjQrUVhOKy9qZS9URldKWXRDYlRH
            bm5CMjZkOGlRdlhLektMWXluelBVbVkKLS0tIFAzQ3R6b2RwZDNzTkQweGwrLzdX
            OU4vLzArUUszcUVLMlVwdUljcnRmVU0K1NMBIQ6OlEEXZLn6QYqjFW9O6xqFg8OQ
            7M8BvFYtE3MhseK1+4/IE4Kgp/oTl/04aTZNfXqVvZS2s4ZDXPqB/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tssd45ekk8u3ppjsd56hype3hdz38fw3zpcr0tgf9gsxk3gfqcvqp8lv5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMnM5d29KTDUvQnphbVV3
            dHpNVS9wdW1JcmY1M1dGTHg3OTJNMEUzRWlFClR4MFhhYnpWWVhCVjJrNklUWVVv
            NEhvZDFTdFZ2ZlY5eTloRDdUL21tYTQKLS0tIDdqSGcxOGpsNWZWU2tuejVrc080
            aHhaVmVVajA1Q3VsME1JZkcwYnY1RmsKXM3QQfJgjn3JQk64scxBa5ApEZduBl2S
            9z8GbwEIRyF1TNH+lCxZ0/PIl9NjEQ7ag3FtE5C2nbMdjv+DmG2VFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17xcewrwf70m4c85m5m2u9xkdt695gkznq3zwtg6z3pcsm9z9fqcq5lf7tr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRHZSbWs2UmQ0dUxPL2p6
            Z2ZXK0dUSHUzZ0NNN0RiN0JvZktjbDgyaWxvCm01V09HL0V2cHArVWlCUDVuUXlH
            R1hXakxOYVlKMVJ2UXZMQUpJUnpLMWsKLS0tIDNBaDVaRzFtZS9yV0FKK0dGRkxE
            Ly8zYlBwQWZzaEdjdTF1amd2Y0xxcUkK2A8G289aKHht8BiaaNPgE9TvZvWZ/N5O
            gFwqooq1xhsqp0r5DPOJuurNCDCGg8E1x8S7M+U7hojiYYqodV+qxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hwjjapf87d5m8e9seutcyk9fdx2m92wnjhhlzy8r3t4tqcvysppsvwk5we
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyak4rRkE4emljdGw3Z3lK
            SDJobHBPb3I3aDljSlhPSDlmWVg4Z0lqUVNBCkFMVFZlU2JHRlJkaExrdmpTelhz
            SFNCOWdQU0VqTjFqM2d5dWhKMUhKYWsKLS0tIFNEazdDc1l1TnNOMXZROWNpMVdM
            anR4eHAwRS9Ka2piQzYycGllZ1VWalEKpKOk8rTIgxDCjmTMnnj7gaJ90Nwf520F
            Orr8ql+Ji5S4doRF5k5x4nwhHjEQwt0fzsWxG4HzGctDQR6QPL6Kdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T12:40:36Z"
    mac: ENC[AES256_GCM,data:/Jq/yo3fKvvwaIWFnf/zVMq5ajE3OrvDNuz4UfioekkV+KmJEfx23XRdWZWEhPmYmxwD7Xt2U1VMFEeLpYUqrVX/+suhcUTtDm9MmhShZlMdGjBXXidI3pmC4thK9GdOSjjrW0ArhSOrdIqBH/h8xOegUOgfvyNkiXWaR0SV0nY=,iv:uXf/Uq9WkGzBGbmZFbVT3HhGL/mUZ7brFulcP+MI2KI=,tag:xqZQKxV+B/30dBqqjUjX6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
