{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.looniversity.desktop.environment.lde;

  startScript = pkgs.writeScript "startlwm" ''
    #! ${pkgs.zsh}/bin/zsh
    # run daemon-reload so that sops generated templates in ~/.config/environment.d
    # are read (they are generated by sops too late for the standard systemd env generator)
    systemctl --user daemon-reload
    systemctl --user unset-environment DISPLAY WAYLAND_DISPLAY
    ${pkgs.zsh}/bin/zsh --login -c "${pkgs.systemd}/bin/systemctl --user import-environment PATH XDG_DATA_DIRS"
    exec systemctl --user --wait start lwm.service
  '';

  inherit (lib)
    mkEnableOption
    mkIf
    mkOption
    types
    ;
  inherit (lib.looniversity) enabled;
in
{
  options.looniversity.desktop.environment.lde = {
    enable = mkEnableOption "Looniversity desktop environment";

    python = mkOption {
      type = types.package;
      default = pkgs.python3;
    };
  };

  config = mkIf cfg.enable {
    looniversity = {
      desktop = {
        gsettings-schema = enabled;
        display_manager.greetd = enabled;
        greeter.tuigreet = enabled // {
          script = "${startScript}";
        };

        lockscreen.swaylock = enabled;

        window_manager.lwm = {
          enable = true;
          python = config.looniversity.desktop.environment.lde.python;
          extraPythonPackages = ps: [
            # Extra widgets
            ps.qtile-extras

            # Packages required by widgets
            ps.aiohttp
            ps.dbus-fast # Bluetooth
            ps.iwlib # Wifi
            ps.psutil # CPU
            ps.pulsectl-asyncio # PulseVolume

            # Packages required by config
            ps.pyyaml
            ps.pydantic
          ];
        };
      };

      security.polkit = enabled;
    };

    systemd.user.targets.lde-session = {
      description = "Looniversity desktop environment session";
      documentation = [ "man:systemd.special(7)" ];
      bindsTo = [ "graphical-session.target" ];
      wants = [ "graphical-session-pre.target" ];
      after = [ "graphical-session-pre.target" ];
    };

    programs = {
      dconf = enabled;
      xwayland.enable = true;
    };

    services.xserver.desktopManager.runXdgAutostartIfNone = lib.mkDefault true;

    systemd.user.services.xdg-desktop-portal-wlr = {
      partOf = [ "lde-session.target" ];
      after = [ "lde-session.target" ];
    };

    xdg.portal = {
      enable = true;
      config = {
        common = {
          default = [ "gtk" ];
          "org.freedesktop.impl.portal.Screenshot" = [ "wlr" ];
          "org.freedesktop.impl.portal.ScreenCast" = [ "wlr" ];
        };
      };
      extraPortals = [
        pkgs.xdg-desktop-portal-gtk
        pkgs.xdg-desktop-portal-wlr
      ];
      wlr = enabled;
    };
  };
}
